version: "3.8"

services:
    api-chats:
        build: .
        environment:
            DB_CONNECTION: Host=db-chats;Database=Chats;Port=5432;Username=postgres;Password=postgres
        ports:
            - "8080:8080"
        depends_on:
            db-chats:
                condition: service_healthy
        networks:
            - default
            - isolated_db_chats
    db-chats:
        image: postgres:13
        env_file:
            - ./.env.prod
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d Chats -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - isolated_db_chats

networks:
    isolated_db_chats:
        internal: true
