# Stage 1: Build the artifact
FROM gradle:8.9.0-jdk21-alpine AS build
# Set the working directory to the project directory
WORKDIR /home/gradle/src
COPY ./ ./
# Build the project
RUN ./gradlew build -x test