apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.name }}
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.ingress.host }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.ingress.name }}
spec:
  hosts:
  - "{{ .Values.ingress.host }}"
  gateways:
  - {{ .Values.ingress.name }}
  http:
  - match:
    - uri:
        exact: "/api/ws"
    route:
    - destination:
        host: api-gateway
        port:
          number: 8080
    websocketUpgrade: true
  - match:
    {{- range .Values.ingress.paths }}
    - uri:
        prefix: "{{ .path }}"
    route:
    - destination:
        host: "{{ .service.name }}"
        port:
          number: {{ .service.port }}
    {{- end }}
