ingress:
  name: example-ingress
  host: example.com
  tls:
    enabled: false
    secretName: example-tls

roleManager:
  api:
    name: api-role-manager
    env:
    - name: TYPEORM_HOST
      value: db-role-manager-svc
    - name: TYPEORM_PORT
      value: "5432"
    - name: TYPEORM_USERNAME
      value: postgres
    - name: TYPEORM_PASSWORD
      value: postgres
    - name: TYPEORM_DATABASE
      value: db_role_manager
    deployment:
      replicas: 1
      name: role-manager-deployment
    image:
      repository: docker.io/nicklnick/role-manager
      tag: prod-202406231937
    service:
      name: role-manager-svc
    ingress:
      path: /users
      pathType: Prefix
    servicePort: 8080
    containerPort: 3000

  db:
    name: db-role-manager
    deployment:
      replicas: 1
      name: db-role-manager-deployment
      volume:
        mountPath: /var/lib/postgresql/data
        name: postgresdata
    image:
      repository: postgres
      tag: 13
    service:
      name: db-role-manager-svc
    pv:
      name: db-role-manager-pv
      app: db-role-manager
      path: /data/postgresql
      accessMode: ReadWriteOnce
      size: 500Mi
    pvc:
      name: db-role-manager-pvc
      accessMode: ReadWriteOnce
      size: 500Mi
    pgVariables:
      name: db_role_manager
      user: postgres
      password: postgres
    servicePort: 5432
    containerPort: 5432

chats:
  api:
    name: api-chats
    env:
    - name: TYPEORM_HOST
      value: db-chats-svc
    - name: TYPEORM_PORT
      value: "5432"
    - name: TYPEORM_USERNAME
      value: postgres
    - name: TYPEORM_PASSWORD
      value: postgres
    - name: TYPEORM_DATABASE
      value: db_chats
    deployment:
      replicas: 1
      name: chats-deployment
    image:
      repository: docker.io/nicklnick/chats
      tag: CHANGE_ME # complete
    service:
      name: chats-svc
    ingress:
      path: /chats
      pathType: Prefix
    servicePort: 8080
    containerPort: 3000

  db:
    name: db-chats
    deployment:
      replicas: 1
      name: db-chats
      volume:
        mountPath: /var/lib/postgresql/data
        name: postgresdata
    image:
      repository: postgres
      tag: 13
    service:
      name: db-chats-svc
    pv:
      name: db-chats-pv
      app: db-chats
      path: /data/postgresql
      accessMode: ReadWriteOnce
      size: 2Gi
    pvc:
      name: db-chats-pvc
      accessMode: ReadWriteOnce
      size: 500Mi
    pgVariables:
      name: db_chats
      user: postgres
      password: postgres
    servicePort: 5432
    containerPort: 5432
