# Enable or disable microservices
role-manager:
  enabled: false
chats:
  enabled: false
document-manager:
  enabled: false
embeddings:
  enabled: true
postgres:
  enabled: true
buildApi: false

# Configure db
db:
  env:
  - name: POSTGRES_DB
    value: db_embeddings
  - name: POSTGRES_USER
    value: langchain
  - name: POSTGRES_PASSWORD
    value: langchain
  deployment:
    replicas: 1
    name: db-embeddings-deployment
    volume:
      mountPath: /var/lib/postgresql/data
      name: postgresdata
  image:
    repository: pgvector/pgvector
    tag: pg16
  service:
    name: db-embeddings-svc
  pvc:
    name: db-embeddings-pvc
    accessMode: ReadWriteOnce
    size: 12Gb
  servicePort: 5432
  containerPort: 5432
