apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.db.deployment.name }}"
spec:
  replicas: {{ .Values.db.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.db.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.db.name }}"
    spec:
      containers:
        - name: "{{ .Values.db.name }}"
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          env:
          {{- range .Values.api.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          volumeMounts:
            - mountPath: "{{ .Values.db.deployment.volume.mountPath }}"
              name: "{{ .Values.db.deployment.volume.name }}"
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          {{- if .Values.postgres.enabled }}
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-d"
                - "$(POSTGRES_DB)"
                - "-U"
                - "$(POSTGRES_USER)"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
      volumes:
        - name: "{{ .Values.db.deployment.volume.name }}"
          persistentVolumeClaim:
            claimName: "{{ .Values.db.pvc.name }}"

