{{- if .Values.buildApi -}}
apiVersion: v1
kind: Service
metadata:
    name: "{{ .Values.api.service.name }}"
spec:
    selector:
        app: "{{ .Values.api.name }}"
    ports:
        - protocol: TCP
          port: {{ .Values.api.servicePort }} # arbitrary
          targetPort: {{ .Values.api.containerPort }} # where the app is listening
{{- else -}}
  # dont build api
{{- end -}}