include:
  - local: 'cicd-pipeline-template.yml'
    inputs:
      image-name: 'message-history'
      env-image-name: 'MESSAGE_HISTORY'
      environment: 'prod'
      directory-name: 'message-history'