version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-chatHistory-fromCompose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatsHistory
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: my-csharp-api
    container_name: my-csharp-api
    build:
      context: ./
    environment:
      DB_CONNECTION: Host=postgres;Database=chatsHistory;UserId=postgres;Password=postgres
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
