apiVersion: v2
name: app
description: Helm chart to deploy de entire App

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: ingress-nginx
  alias: ingress-nginx
  version: 4.10.1
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: document-manager
  alias: document-manager
  version: 0.1.0
  repository: "file://charts/document-manager"
- name: api-gateway
  alias: api-gateway
  version: 0.1.0
  repository: "file://charts/api-gateway"
- name: embeddings
  alias: embeddings
  version: 0.1.0
  repository: "file://charts/embeddings"
- name: role-manager
  alias: role-manager
  version: 0.1.0
  repository: "file://charts/role-manager"
- name: chats
  alias: chats
  version: 0.1.0
  repository: "file://charts/chats"
- name: rabbitmq
  alias: rabbitmq
  version: 0.1.0
  repository: "file://charts/rabbitmq"
