### INGRESS ###
name: app
ingress:
  name: istio-gateway
  host: example.com
  paths:
  - service:
      name: api-gateway
      port: 8080
    path: /api
    pathType: Prefix

### SUBCHARTS ###
role-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-2
  db:
    statefulSet:
      replicas: 1

document-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-7
  db:
    statefulSet:
      replicas: 1

embeddings:
  db:
    statefulSet:
      replicas: 1

chats:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-4
  db:
    statefulSet:
      replicas: 1

message-history:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-4
  db:
    statefulSet:
      replicas: 1

llm-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-4

api-gateway:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-6

chat-session:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-4
  db:
    statefulSet:
      replicas: 1
