### INGRESS ###
name: app
ingress:
  name: example-ingress
  host: example.com
  tls:
    enabled: false
    secretName: example-tls
  paths:
    roleManager:
      api:
        service:
          name: api-role-manager-svc
          port: 8080
        path: /users
        pathType: Prefix
    documentManager:
      api:
        service:
          name: api-document-manager-svc
          port: 8000
        path: /documents
        pathType: Prefix
    chats:
      api:
        service:
          name: api-chats-svc
          port: 8080
        path: /chats
        pathType: Prefix

### SUBCHARTS ###
role-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: prod-202406231937
  db:
    statefulSet:
      replicas: 1

document-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid
  db:
    statefulSet:
      replicas: 1

embeddings:
  db:
    statefulSet:
      replicas: 1

chats:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid
  db:
    statefulSet:
      replicas: 1
