### INGRESS ###
name: app
ingress:
  name: example-ingress
  host: example.com
  tls:
    enabled: false
    secretName: example-tls
  paths:
  - service:
      name: api-gateway
      port: 8080
    path: /api
    pathType: Prefix

### SUBCHARTS ###
role-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid
  db:
    statefulSet:
      replicas: 1

document-manager:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-3
  db:
    statefulSet:
      replicas: 1

embeddings:
  db:
    statefulSet:
      replicas: 1

chats:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-3
  db:
    statefulSet:
      replicas: 1

message-history:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid
  db:
    statefulSet:
      replicas: 1

api-gateway:
  api:
    deployment:
      replicas: 1
    image:
      tag: test-noid-4
