apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.db.statefulSet.name }}"
spec:
  replicas: {{ .Values.db.statefulSet.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.db.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.db.name }}"
    spec:
      containers:
        - name: "{{ .Values.db.name }}"
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          env:
          {{- range .Values.db.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          volumeMounts:
            - mountPath: "{{ .Values.db.statefulSet.volume.mountPath }}"
              name: "{{ .Values.db.statefulSet.volume.name }}"
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-d"
                - "db_message_history"
                - "-U"
                - "postgres"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: "{{ .Values.db.statefulSet.volume.name }}"
          persistentVolumeClaim:
            claimName: "{{ .Values.db.pvc.name }}"

