apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.roleManager.api.deployment.name }}"
spec:
  replicas: {{ .Values.roleManager.api.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.roleManager.api.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.roleManager.api.name }}"
    spec:
      containers:
        - name: "{{ .Values.roleManager.api.name }}"
          image: "{{ .Values.roleManager.api.image.repository }}:{{ .Values.roleManager.api.image.tag }}"
          env:
            - name: TYPEORM_HOST
              value: "db-role-manager-svc"
            - name: TYPEORM_PORT
              value: "5432"
            - name: TYPEORM_USERNAME
              value: "postgres"
            - name: TYPEORM_PASSWORD
              value: "postgres"
            - name: TYPEORM_DATABASE
              value: "db_role_manager"
          ports:
            - containerPort: {{ .Values.roleManager.api.containerPort }}
