###
# Test creating a document
POST http://127.0.0.1:8000/documents
Content-Type: application/json

{
  "title": "Test Document",
  "content": "SGVsbG8gV29ybGQh"
}

###

# Test getting a document by ID
GET http://127.0.0.1:8000/documents/1
Accept: application/json

###

# Test getting a document that does not exist (replace {non_existent_document_id} with a non-existent ID)
GET http://127.0.0.1:8000/documents/10000
Accept: application/json

