spring:
  application:
    name: spring-chat-session
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379

message-history:
  api: http://localhost:5128
