apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672

    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
  definitions.json: |
    {
      "policies": [
        {
          "vhost": "/",
          "name": "ha-fed",
          "pattern": ".*",
          "definition": {
            "federation-upstream-set": "all",
            "ha-sync-mode": "automatic",
            "ha-mode": "nodes",
            "ha-params": [
              "rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local",
              "rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local",
              "rabbit@rabbitmq-2.rabbitmq.default.svc.cluster.local"
            ]
          },
          "priority": 1,
          "apply-to": "queues"
        }
      ],
      "federation-upstream-sets": {
        "all": [
          {
            "name": "upstream1",
            "uri": "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672",
            "reconnect-delay": 5
          }
        ]
      }
    }