version: '3.8'

services:
  api-role-manager:
    build: ../..
    command: test:e2e
    env_file:
      - .env
    profiles:
      - all
      - role-manager
    depends_on:
      db-role-manager:
        condition: service_healthy
    networks:
      - default
      - isolated_db_role_manager

  db-role-manager:
    image: 'postgres:13'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d db_role_manager_test -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
    profiles:
      - all
      - role-manager
    networks:
      - isolated_db_role_manager

networks:
  isolated_db_role_manager:
    internal: true
