name: role-manager
# Configure api
api:
  name: api-role-manager
  env:
  - name: TYPEORM_HOST
    value: db-role-manager-svc
  - name: TYPEORM_PORT
    value: "5432"
  - name: TYPEORM_USERNAME
    value: postgres
  - name: TYPEORM_PASSWORD
    value: postgres
  - name: TYPEORM_DATABASE
    value: db_role_manager
  deployment:
    replicas: 1
    name: api-role-manager-deployment
  image:
    repository: docker.io/nicklnick/role-manager
    tag: prod-202406231937
  service:
    name: api-role-manager-svc
  servicePort: 8080
  containerPort: 3000

# Configure db
db:
  name: db-role-manager
  env:
  - name: POSTGRES_DB
    value: db_role_manager
  - name: POSTGRES_PASSWORD
    value: postgres
  - name: POSTGRES_USER
    value: postgres
  statefulSet:
    replicas: 1
    name: db-role-manager-stateful-set
    volume:
      mountPath: /var/lib/postgresql/data
      name: postgresdata
  image:
    repository: postgres
    tag: 16
  service:
    name: db-role-manager-svc
  pv:
    name: db-role-manager-pv
    path: /data/role-manager/postgresql
    accessMode: ReadWriteMany
    size: 100Mi
  pvc:
    name: db-role-manager-pvc
    accessMode: ReadWriteMany
    size: 100Mi
  servicePort: 5432
  containerPort: 5432
