services:
  test:
    build: ../../
    container_name: test-component
    entrypoint: sh -c "pytest src/test/component/test.py"
    env_file: ../../.env
    depends_on:
      - mocked-llm-manager
    networks:
      - rabbit-internal-network

  mocked-llm-manager:
    build: ../../
    container_name: mocked-llm-manager
    entrypoint: sh -c "python -m src.test.component.mocked_app"
    env_file: ../../.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit-internal-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: component-test-rabbitmq
    networks:
      - rabbit-internal-network
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  rabbit-internal-network:
    internal: true